name: Deploy via ftp

on:
  push:
    branches:
      - main  # ajuste conforme a branch que você deseja monitorar para deploys

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install  # ou yarn, dependendo do seu projeto

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ftp.redebloomie.com.br
          user: redebloomie2
          password: ${{ secrets.PASS }}
          remoteDir: "https://github.com/redebloomie/bloomie-website"
          localDir: "dist"  # ajuste conforme o diretório do seu projeto a ser enviado
